### ISSUE TITLE
solpotato-server.toml doesn't exists

### ISSUE THREAD

**Issue by GatoLeyo** [Kevun1/Spice-of-Life-Potato-Edition#3]
The file was never generated, i only have the client.toml

**Comment by Kevun1** [comment]
Server configs are not located in the regular `config` folder in Forge post-1.12. 

Every single save file has its own copy of its server configs, located in `saves/[world name]/serverconfig`. If you want to make it so that all new worlds you create use the same configs, place a copy of `solpotato-server.toml` in the `defaultconfigs` folder.
